server:
  tomcat:
    max-http-post-size: -1
spring:
  profiles:
    active: dev
  application:
    name: medical
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  datasource:
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 6000
    maxPoolPreparedStatementPerConnectionSize: 20
    timeBetweenEvictionRunsMillis: 6000
    driver-class-name: com.mysql.jdbc.Driver     #com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true    #当遇到同样名字的时候，是否允许覆盖注册
  cache:
    type: redis  # 可选 redis、none、ehcache
  redis:
     timeout: 20000     # 链接超时时间（毫秒）
     lettuce:
       pool:
         max-idle: 8        # 最大空闲连接
         min-idle: 0        # 最小空闲链接
         max-active: 8      # 最大连接数（负数表示没有限制）
         max-wait: -1       # 最大阻塞等待时间（负数表示没有限制）
  hosconfig:
    hos-token-url: http://61.172.179.73:41150 # 获取院版token的url
    hos-data-server-url: http://61.172.179.73:41149 #获取院版数据的url
    app-id: Oh_Newtouch_Clinic # 院版对应的appid
    organize-id: 6d5752a7-234a-403e-aa1c-df8b45d3469f #院版对应的organizeid
mybatis:
  mapperLocations: classpath*:/mapper/**/*.xml
  configuration:
    cacheEnabled: true     #使全局的映射器启用或禁用缓存
    lazyLoadingEnabled: true    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    aggressiveLazyLoading: true  #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    multipleResultSetsEnabled: true   #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    useColumnLabel: true              #是否可以使用列的别名 (取决于驱动的兼容性) default:true
    useGeneratedKeys: false           #允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    autoMappingBehavior: PARTIAL      #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    defaultExecutorType: SIMPLE       #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    mapUnderscoreToCamelCase: true    #使用驼峰命名法转换字段。
    localCacheScope: SESSION          #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    jdbcTypeForNull: NULL             #设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  #  数据库的种类
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params=count: countSql
  page-size-zero: true
logging:
  level:
    com.geeke.gen.dao.*: debug
    com.geeke.admin.dao.*: debug
    com.geeke.sys.dao.*: debug
    org.camunda: debug
    com.geeke.gen: debug

genConfigure:
  rootPath: C:\Users\developer\IdeaProjects\medical #代码生成地址配置
  dbName: mysql                          #数据库类型:  mysql/oracle/mssql

